name: Test

on:
  pull_request:
  push:
    branches: [ master, main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: ./
        with:
          input-files: test/example.pkl, test/folder with space/test.pkl
          output-folder: test/output
      - run: |
          ls -lR test
          cat test/output/java/Example.java