name: Move a major tag to the latest release

on:
  push:
    tags:
      - v**
    tags-ignore:
      - v*-*

jobs:
  tag:
    name: Move major tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: phwt/major-tagging-action@v1